<?php
/*
* The createApplication view processes form data for job application creation.
* Input data is sanitized, validated and tested for errors. 
* Additional functionality has been added to improve UX ($applicationData 
* ensures only invalid fields are cleared in case of field validation errors)
*
* The application creation process utilises two-layer error handling:
*   - Layer 1: Handles expected user errors through validator objects
*   - Layer 2: Handles unexpected system exceptions
*
* In both cases, the user gets feedback through $errorMessages, ensuring 
* that technical details stay hidden in case of system errors. 
*/

require_once '../../../../assets/inc/functions.php';
require_once '../../../../assets/lib/validator.php';
require_once '../../../../assets/inc/database/db.php';
require_once '../../../../assets/inc/database/jobApplicationSql.php';

$errorMessages = [];
$successMessage = '';
$applicationData = []; // Store sanitized form data for repopulation in case of validation errors

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['createApplication'])) {
    
    // Store sanitized form data (only user-provided fields)
    $applicationData = [
        'jobPostId' => cleanFormInput($_POST['jobPostId']),
        'coverLetter' => cleanFormInput($_POST['coverLetter'])
    ];

    $validator = new Validator();
    
    // Layer 1: Validate sanitized data
    // Validate jobPostId
    if (empty($applicationData['jobPostId']) || !filter_var($applicationData['jobPostId'], FILTER_VALIDATE_INT)) {
        $errorMessages['jobPostId'] = "Invalid job post ID";
    }
    
    // Validate cover letter (required, min/max length)
    if (empty($applicationData['coverLetter'])) {
        $errorMessages['coverLetter'] = "Cover letter is required";
    } elseif (strlen($applicationData['coverLetter']) < 50) {
        $errorMessages['coverLetter'] = "Cover letter must be at least 50 characters";
    } elseif (strlen($applicationData['coverLetter']) > 5000) {
        $errorMessages['coverLetter'] = "Cover letter must not exceed 5000 characters";
    }
    
    // Merge validator errors with manual validation errors
    $errorMessages = array_merge($errorMessages, $validator->getErrors());
    
    if (empty($errorMessages)) {
        try {
            // Auto-generated fields (not from user input):
            // - applicantId: Get from session (TODO)
            $applicationData['applicantId'] = 1; // TODO: Get from session after login is implemented
            
            // - applicationId: Auto-generated by database (AUTO_INCREMENT)
            
            // - status: Automatically set to 'submitted'
            $applicationData['status'] = "submitted";
            
            // - submitDate: Automatically set to current timestamp
            $applicationData['submitDate'] = date("Y-m-d H:i:s");
            
            // - jobTitle: Will be fetched from jobPost when clicking from ViewJob (TODO: future feature)
            $applicationData['jobTitle'] = ""; // Placeholder until ViewJob integration
            
            // Save application to database
            updateJobApplication($pdo, $applicationData, $errorMessages);
            
            // Only show success if no database errors occurred
            if (empty($errorMessages)) {
                $successMessage = "Application submitted successfully!";
                $applicationData = []; // Clear form data on success
            }
            
        // Layer 2: handle and log unexpected system/db exceptions
        } catch (Exception $e) {
            $errorMessages['registration'] = "An error occurred while submitting your application"; 
            error_log("Job application creation error: " . $e->getMessage());
        }
        // If validation fails, $applicationData remains populated
    }   
}
?>



<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create Job Application</title>
    <link rel="stylesheet" href="../../../../assets/css/style.css">
</head>
<body class="form-page-body">
    <div class="form-page-container">        
        <div class="form-page-content">
            
            <!-- Success message display -->
            <?php if (!empty($successMessage)): ?>
                <div class="success-message"><?= htmlspecialchars($successMessage) ?></div>
            <?php endif; ?>

            <!-- Error messages display -->
            <?php foreach (['registration', 'database'] as $errorType): ?>
                <?php if (isset($errorMessages[$errorType])): ?>
                    <div class="error-message"><?= htmlspecialchars($errorMessages[$errorType]) ?></div>
                <?php endif; ?>
            <?php endforeach; ?>
            
            <!-- Job Application Form -->
            <form method="post" action="<?=htmlspecialchars($_SERVER['PHP_SELF']);?>" class="job-application-form compact-form" autocomplete="off" novalidate>

            <!-- Form Grid Layout -->
            <div class="form-grid">
                <!-- Job Post ID -->
                <div class="form-group">
                    <label for="jobPostId">Job Post ID *</label>
                    <input type="number" id="jobPostId" name="jobPostId" min="1" autocomplete="off" 
                           placeholder="Enter job post ID"
                           value="<?= preserveFormValue($applicationData, 'jobPostId') ?>" 
                           <?= isset($errorMessages['jobPostId']) ? 'class="error"' : '' ?>>
                    <small class="field-hint">TODO: This will be auto-filled when clicking from ViewJob</small>
                    <?= displayErrorMessage($errorMessages, 'jobPostId') ?>
                </div>

                <!-- Full Width - Cover Letter -->
                <div class="form-group full-width">
                    <label for="coverLetter">Cover Letter *</label>
                    <textarea id="coverLetter" name="coverLetter" rows="8" autocomplete="off" 
                              placeholder="Explain why you're interested in this position and what qualifies you... (minimum 50 characters)"
                              <?= isset($errorMessages['coverLetter']) ? 'class="error"' : '' ?>><?= preserveFormValue($applicationData, 'coverLetter') ?></textarea>
                    <small class="field-hint">Minimum 50 characters, maximum 5000 characters</small>
                    <?= displayErrorMessage($errorMessages, 'coverLetter') ?>
                </div>
            </div>

            <!-- Form Actions -->
            <div class="form-actions">
                <button type="button" class="btn btn-secondary" onclick="history.back()">Cancel</button>
                <button type="submit" name="createApplication" class="btn btn-primary">Submit Application</button>
            </div>
        </form>
        </div>
    </div>
</body>
</html>